package model.environment.animals.attributes;

public record AnimalOrganismAttributes(AnimalVitalsAttributes animalVitalsAttributes, AnimalPositionAttributes animalPositionAttributes, AnimalNutritionAttributes animalNutritionAttributes, AnimalReproductionAttributes animalReproductionAttributes) {

}